### ISSUE TITLE
About the parameter "subtask_size"

### ISSUE THREAD

**Issue by nxchenbnu** [uqbingliu/DivEA#1]
Thanks for the open source code and nicely written essay :)!

The setting of "subtask_size" seems different. For example, in "run_over_perf_vs_sbp.sh", it's in ctx_size_dict=( ['fr']=9594 ['ja']=10323 ['zh']=9421 ['wd']=28693 ['yg']=29521 ). What is the actual meaning of the "subtask_size" and how we can get it?

**Comment by uqbingliu** [comment]
Hey. Thanks for your question.

The parameter "subtask_size" means the number of entities in a subtask (in two KGs). We set this parameter to control the need for GPU memory. A larger value leads to better performance if your GPU memory is sufficient.

The reason that "subtask_size" is set differently in our scripts is: we make our method have the same subtask size as the baselines, which cannot control the subtask size. We run the baselines first and then check the sizes of their produced subtasks. Afterwards, we set our subtask size as the average size of them.

If you do not need to align your "subtask_size" with other methods, you can set it freely under the limitation of your GPU memory.

**Comment by Summerislab** [comment]
Thank you for your work again ! 
I have an another question about the running time in your paper. 

I have noticed that in Table 5(Time cost of The EA division), DivEA achieved a high level quality of running time which only causes 398 seconds in 100K datasets. I wonder the time here represents the total training time, right? If not so, can you explain the what it includes? 

Thank you again!

**Comment by uqbingliu** [comment]
In Table 4 and 5, we aim to show extra time consumption apart from running an EA model. The "EA" column represents running EA model, while other column represents task division by each method.

In DivEA framework, the time costs of task division include three parts: (1) dividing unmatched source entities t1. (2) counterpart discovery of subtask i: t2_i . (3) build context graphs of subtask i: t3_i . 

* DivEA column represents using DivEA in a single-machine setting. The time of task division is: t1 + \sum_i {t2_i+t3_i}
* DivEA (par.) column represents using DivEA in parallelism setting.  The time of task division is: t1 + \max_i {t2_i+t3_i}
